apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: nav-mangfold-frontend      
  namespace: heda                   
  labels:
    team: heda
spec:       
  port: 3000                    
  ingresses:
    - https://mangfold.intern.dev.nav.no
    - https://mangfold.ansatt.dev.nav.no
  replicas:
    min: 1
    max: 2
  resources:
    requests:
      cpu: 12m
      memory: 128Mi
    limits:
      memory: 255Mi
  accessPolicy:
    outbound:
      rules:
        - application: nav-dekoratoren
          namespace: personbruker
  #Legger de senere når vi har de klærer
  # liveness:
  #  path: /
   # initialDelay: 20
  #readiness:
   # path: /
    #initialDelay: 20
