name: Build and deploy

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    name: Build, push and deploy
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      actions: read

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          registry-url: "https://npm.pkg.github.com"
      - name: NPM install
        run: npm install
        env:
          NPM_TOKEN: ${{ secrets.READER_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
      - name: NPM build
        run: npm run build
        env:
          NPM_TOKEN: ${{ secrets.READER_TOKEN }}
      - name: Push docker image to GAR
        uses: nais/docker-build-push@v0
        id: docker-build-push-frontend
        with:
          team: heda
          docker_context: .
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}

      - name: Deploy to Nais
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp                     
          RESOURCE: .nais/app.yaml          
          IMAGE: ${{ steps.docker-build-push-frontend.outputs.image }}
